### PR TITLE
Bump openmdx patch version to 2.18.9

### PR DESCRIPTION
**Pull request by javac9**
There was a regression case in OpenMDX which caused a bump in patch version. If you were to use version `2.18.8` of OpenMDX instead of actually used version `2.18-20231111` to build OpenCRX before upgrading to `5.3.0`, I'm pretty confident it wouldn't have worked.

See https://github.com/openmdx/openmdx/commits/openmdx-v2.18.9

### CODE REVIEW

**Review by wfro64 — COMMENTED** [review]
opencrx-v5.3.0 was built with openmdx-v2.18.8 https://github.com/opencrx/opencrx/blob/opencrx-v5.3.0/build.properties

The current master (which is not released) is built with openmdx.version=2.18-20231111. Will  soon upgrade to openmdx-2.18.9 (or later) ...

**Comment by javac9** [comment]
Then I wonder how that was possible. I tried building OpenCRX with `2.18.8` locally, was failing just like some other projects.

**Comment by wfro64** [comment]
```
> java --version
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu122.04, mixed mode, sharing)

> git clone https://github.com/opencrx/opencrx.git opencrx
> cd opencrx
> git checkout opencrx-v5.3.0
> ./gradlew --refresh-dependencies clean
> ./gradlew --refresh-dependencies assemble

BUILD SUCCESSFUL in 1m 24s
29 actionable tasks: 29 executed
```

**Comment by javac9** [comment]
Sorry for the confusion, it's the schema generation that is failing with `2.18.8`

```
...
[ant:mappingtool] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ant:mappingtool] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ant:mappingtool] Caused by: <openjpa-3.2.2-re5933d6 fatal user error> org.apache.openjpa.util.MetaDataException: The id class specified by type "class org.opencrx.kernel.jpa3.Segment$Slice" does not match the primary key fields of the class.  Make sure your identity class has the same primary keys as your persistent type, including pk field types. Mismatched property: "openmdxjdoIdentity"
[ant:mappingtool] 	at org.apache.openjpa.meta.ClassMetaData.validateAppIdClassPKs(ClassMetaData.java:2228)
[ant:mappingtool] 	at org.apache.openjpa.meta.ClassMetaData.validateAppIdClass(ClassMetaData.java:2102)
[ant:mappingtool] 	at org.apache.openjpa.meta.ClassMetaData.validateIdentity(ClassMetaData.java:2038)
[ant:mappingtool] 	at org.apache.openjpa.meta.ClassMetaData.validateMeta(ClassMetaData.java:1950)
[ant:mappingtool] 	at org.apache.openjpa.meta.ClassMetaData.resolve(ClassMetaData.java:1811)
[ant:mappingtool] 	at org.apache.openjpa.meta.MetaDataRepository.processBuffer(MetaDataRepository.java:838)
[ant:mappingtool] 	at org.apache.openjpa.meta.MetaDataRepository.resolveMeta(MetaDataRepository.java:734)
[ant:mappingtool] 	at org.apache.openjpa.meta.MetaDataRepository.resolve(MetaDataRepository.java:655)
[ant:mappingtool] 	... 185 more
[ant:mappingtool] NestedThrowables:
[ant:mappingtool] <openjpa-3.2.2-re5933d6 fatal user error> org.apache.openjpa.util.MetaDataException: Attempt to map "org.opencrx.kernel.jpa3.Segment$Slice.openmdxjdoIdentity" failed: the owning entity is not mapped.
[ant:mappingtool] 	at org.apache.openjpa.jdbc.meta.MappingInfo.assertTable(MappingInfo.java:632)
[ant:mappingtool] 	at org.apache.openjpa.jdbc.meta.MappingInfo.createForeignKey(MappingInfo.java:1084)
[ant:mappingtool] 	at org.apache.openjpa.jdbc.meta.ValueMappingInfo.getTypeJoin(ValueMappingInfo.java:117)
...
```

**Comment by wfro64** [comment]
Correct.

`./gradlew -Pdatabase.name=hsqldb-2 create-schema`

does not work with openmdx-v2.18.9 and later. The reason is a missing META-INF/orm.xml in openmdx-base.jar. I have reported this to @DlRTY-HARRY without ticket. I have now made up for this: https://github.com/openmdx/openmdx/issues/98

This is why opencrx master is using openmdx-v2.18-20231111

This bug was detected after releasing opencrx-v5.3.0. opencrx-v5.3.1 will be released when this and other bugs are fixed.

**Comment by javac9** [comment]
I just tried it, the `orm.xml` file was there for openmdx version `2.18.7` through `2.18.9`

I would suggest that you once more try `./gradlew -Pdatabase.name=hsqldb-2 create-schema` with `opencrx-5.3.0` (which has `openmdx-2.18.8`)

It should fail with this: https://github.com/opencrx/opencrx/pull/134#issuecomment-1838155429 from above,

Then update to `openmdx-2.18.9` and the schema generation should work just fine.

If anything diverges from above, then there has to be a concerning flakiness around because I'm getting these really consistently.

**Comment by wfro64** [comment]
See https://github.com/openmdx/openmdx/issues/98 how to reproduce an openmdx build which consistently builds openmdx-base.jar without META-INF/orm.xml. 

opencrx will not be upgraded to something newer than openmdx-v2.18-20231111 until https://github.com/openmdx/openmdx/issues/98 is fixed.

Will close here. Please move discussion to https://github.com/openmdx/openmdx/issues/98

**Pull request closed without merging**
